name: build-image
on:
  push:
    branches:
      - main

# Environment variables available to all jobs and steps in this workflow
env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.2

    - name: Build php image
      run: docker build --target php -t dsutter/azdrupal-php .

    - name: Build web image
      run: docker build --target web -t dsutter/azdrupal-web .

    # Run phpcs
    # drupal-rector
    # drupal-check
    # Run behat tests (selenium)

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DH_DS_USERNAME }}
        password: ${{ secrets.DH_DS_PASSWORD }}

    - name: Push php image
      run: docker push dsutter/azdrupal-php:latest

    - name: Push web image
      run: docker push dsutter/azdrupal-web:latest
